### PR TITLE
add stdout/stderr logging support to unit.application

### PR DESCRIPTION
**Pull request by MVKozlov**

### CODE REVIEW

**Comment by matejart** [comment]
Thank you for this update, @MVKozlov. Just one question: have you perhaps tested that the behavior is unaltered if the two new attributes are not present in the playbook?

**Comment by MVKozlov** [comment]
Yes, if new attributes omitted it also omitted in resulting config
It just copy/paste from 'working_directory' attribute :)

BUT, if installed `UNIT` version do not support these attributes then config with it will be invalid

**Comment by MVKozlov** [comment]
btw, (off topic) have any plans to implement global settings ?
something like `steampunk.unit.settings` ?

**Comment by matejart** [comment]
> Yes, if new attributes omitted it also omitted in resulting config
> It just copy/paste from 'working_directory' attribute :)

Thank you for clarification!

> BUT, if installed `UNIT` version do not support these attributes then config with it will be invalid

That's acceptable.

> btw, (off topic) have any plans to implement global settings ?
> something like `steampunk.unit.settings`?

Unfortunately we currently have no plans for any updates.

**Pull request merged**
